language: node_js
node_js:
  - "stable"
  - "8"
  - "6"

cache:
  directories:
    - node_modules

before_script:
  - npm uninstall typescript --no-save
  - npm uninstall tslint --no-save
  - npm install

script:
  - npm test

after_success:
  - npm run coverage

branches:
  only:
    - master
