language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

before_script:
  - npm install --no-progress

script:
  - npm test

after_success:
  - npm run coverage

branches:
  only:
    - master
